services:  # Remove the "version: '3.8'" line
  # FastAPI Backend
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: heart-disease-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - heart-disease-network

  # Streamlit Dashboard
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: heart-disease-dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_BASE_URL=http://api:8000
    restart: unless-stopped
    networks:
      - heart-disease-network

  # Nginx Reverse Proxy (optional for local testing)
  nginx:
    image: nginx:alpine
    container_name: heart-disease-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - dashboard
    restart: unless-stopped
    networks:
      - heart-disease-network

networks:
  heart-disease-network:
    driver: bridge